# Generated by Django 4.1.3 on 2023-01-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('In_Out_student', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='x', max_length=217),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
