# Generated by Django 4.1.3 on 2023-01-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('In_Out_staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
