# Generated by Django 4.1.3 on 2023-01-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('In_Out_staff', '0006_staff_aadhar_num_staff_email_id_staff_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pswrd',
            field=models.CharField(default='x', max_length=217),
        ),
    ]
